[project]
name = "src"
version = "0.1.0"
description = "Comparison, in terms of time complexity, between the mechanisms of pipelining and fetching all data at once."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "redis>=5.2.1",
]
